%% THIS FILE WAS AUTOMATICALLY GENERATED BY gen_src.pl
%% FROM mappings/MICSFT/WINDOWS/CP1250.TXT AT 2016-08-19
-module(cp1250).
-vsn(20160819).
-export([to_unicode/1, from_unicode/1]).

%% Public functions
to_unicode(16#80) -> 16#20AC;
to_unicode(16#82) -> 16#201A;
to_unicode(16#84) -> 16#201E;
to_unicode(16#85) -> 16#2026;
to_unicode(16#86) -> 16#2020;
to_unicode(16#87) -> 16#2021;
to_unicode(16#89) -> 16#2030;
to_unicode(16#8A) -> 16#0160;
to_unicode(16#8B) -> 16#2039;
to_unicode(16#8C) -> 16#015A;
to_unicode(16#8D) -> 16#0164;
to_unicode(16#8E) -> 16#017D;
to_unicode(16#8F) -> 16#0179;
to_unicode(16#91) -> 16#2018;
to_unicode(16#92) -> 16#2019;
to_unicode(16#93) -> 16#201C;
to_unicode(16#94) -> 16#201D;
to_unicode(16#95) -> 16#2022;
to_unicode(16#96) -> 16#2013;
to_unicode(16#97) -> 16#2014;
to_unicode(16#99) -> 16#2122;
to_unicode(16#9A) -> 16#0161;
to_unicode(16#9B) -> 16#203A;
to_unicode(16#9C) -> 16#015B;
to_unicode(16#9D) -> 16#0165;
to_unicode(16#9E) -> 16#017E;
to_unicode(16#9F) -> 16#017A;
to_unicode(16#A1) -> 16#02C7;
to_unicode(16#A2) -> 16#02D8;
to_unicode(16#A3) -> 16#0141;
to_unicode(16#A5) -> 16#0104;
to_unicode(16#AA) -> 16#015E;
to_unicode(16#AF) -> 16#017B;
to_unicode(16#B2) -> 16#02DB;
to_unicode(16#B3) -> 16#0142;
to_unicode(16#B9) -> 16#0105;
to_unicode(16#BA) -> 16#015F;
to_unicode(16#BC) -> 16#013D;
to_unicode(16#BD) -> 16#02DD;
to_unicode(16#BE) -> 16#013E;
to_unicode(16#BF) -> 16#017C;
to_unicode(16#C0) -> 16#0154;
to_unicode(16#C3) -> 16#0102;
to_unicode(16#C5) -> 16#0139;
to_unicode(16#C6) -> 16#0106;
to_unicode(16#C8) -> 16#010C;
to_unicode(16#CA) -> 16#0118;
to_unicode(16#CC) -> 16#011A;
to_unicode(16#CF) -> 16#010E;
to_unicode(16#D0) -> 16#0110;
to_unicode(16#D1) -> 16#0143;
to_unicode(16#D2) -> 16#0147;
to_unicode(16#D5) -> 16#0150;
to_unicode(16#D8) -> 16#0158;
to_unicode(16#D9) -> 16#016E;
to_unicode(16#DB) -> 16#0170;
to_unicode(16#DE) -> 16#0162;
to_unicode(16#E0) -> 16#0155;
to_unicode(16#E3) -> 16#0103;
to_unicode(16#E5) -> 16#013A;
to_unicode(16#E6) -> 16#0107;
to_unicode(16#E8) -> 16#010D;
to_unicode(16#EA) -> 16#0119;
to_unicode(16#EC) -> 16#011B;
to_unicode(16#EF) -> 16#010F;
to_unicode(16#F0) -> 16#0111;
to_unicode(16#F1) -> 16#0144;
to_unicode(16#F2) -> 16#0148;
to_unicode(16#F5) -> 16#0151;
to_unicode(16#F8) -> 16#0159;
to_unicode(16#F9) -> 16#016F;
to_unicode(16#FB) -> 16#0171;
to_unicode(16#FE) -> 16#0163;
to_unicode(16#FF) -> 16#02D9;
to_unicode(List) when is_list(List) -> [to_unicode(C) || C <- List];
to_unicode(Bin) when is_binary(Bin) -> bin_to_unicode(Bin, <<>>);
to_unicode(Other) -> Other.

from_unicode(16#20AC) -> 16#80;
from_unicode(16#201A) -> 16#82;
from_unicode(16#201E) -> 16#84;
from_unicode(16#2026) -> 16#85;
from_unicode(16#2020) -> 16#86;
from_unicode(16#2021) -> 16#87;
from_unicode(16#2030) -> 16#89;
from_unicode(16#0160) -> 16#8A;
from_unicode(16#2039) -> 16#8B;
from_unicode(16#015A) -> 16#8C;
from_unicode(16#0164) -> 16#8D;
from_unicode(16#017D) -> 16#8E;
from_unicode(16#0179) -> 16#8F;
from_unicode(16#2018) -> 16#91;
from_unicode(16#2019) -> 16#92;
from_unicode(16#201C) -> 16#93;
from_unicode(16#201D) -> 16#94;
from_unicode(16#2022) -> 16#95;
from_unicode(16#2013) -> 16#96;
from_unicode(16#2014) -> 16#97;
from_unicode(16#2122) -> 16#99;
from_unicode(16#0161) -> 16#9A;
from_unicode(16#203A) -> 16#9B;
from_unicode(16#015B) -> 16#9C;
from_unicode(16#0165) -> 16#9D;
from_unicode(16#017E) -> 16#9E;
from_unicode(16#017A) -> 16#9F;
from_unicode(16#02C7) -> 16#A1;
from_unicode(16#02D8) -> 16#A2;
from_unicode(16#0141) -> 16#A3;
from_unicode(16#0104) -> 16#A5;
from_unicode(16#015E) -> 16#AA;
from_unicode(16#017B) -> 16#AF;
from_unicode(16#02DB) -> 16#B2;
from_unicode(16#0142) -> 16#B3;
from_unicode(16#0105) -> 16#B9;
from_unicode(16#015F) -> 16#BA;
from_unicode(16#013D) -> 16#BC;
from_unicode(16#02DD) -> 16#BD;
from_unicode(16#013E) -> 16#BE;
from_unicode(16#017C) -> 16#BF;
from_unicode(16#0154) -> 16#C0;
from_unicode(16#0102) -> 16#C3;
from_unicode(16#0139) -> 16#C5;
from_unicode(16#0106) -> 16#C6;
from_unicode(16#010C) -> 16#C8;
from_unicode(16#0118) -> 16#CA;
from_unicode(16#011A) -> 16#CC;
from_unicode(16#010E) -> 16#CF;
from_unicode(16#0110) -> 16#D0;
from_unicode(16#0143) -> 16#D1;
from_unicode(16#0147) -> 16#D2;
from_unicode(16#0150) -> 16#D5;
from_unicode(16#0158) -> 16#D8;
from_unicode(16#016E) -> 16#D9;
from_unicode(16#0170) -> 16#DB;
from_unicode(16#0162) -> 16#DE;
from_unicode(16#0155) -> 16#E0;
from_unicode(16#0103) -> 16#E3;
from_unicode(16#013A) -> 16#E5;
from_unicode(16#0107) -> 16#E6;
from_unicode(16#010D) -> 16#E8;
from_unicode(16#0119) -> 16#EA;
from_unicode(16#011B) -> 16#EC;
from_unicode(16#010F) -> 16#EF;
from_unicode(16#0111) -> 16#F0;
from_unicode(16#0144) -> 16#F1;
from_unicode(16#0148) -> 16#F2;
from_unicode(16#0151) -> 16#F5;
from_unicode(16#0159) -> 16#F8;
from_unicode(16#016F) -> 16#F9;
from_unicode(16#0171) -> 16#FB;
from_unicode(16#0163) -> 16#FE;
from_unicode(16#02D9) -> 16#FF;
from_unicode(List) when is_list(List) -> [from_unicode(C) || C <- List];
from_unicode(Bin) when is_binary(Bin) -> bin_from_unicode(Bin, <<>>);
from_unicode(Other) -> Other.

%% Private functions
bin_to_unicode(<<>>, Bin) -> Bin;
bin_to_unicode(<<C, Rest/binary>>, Acc) ->
    U = to_unicode(C),
    bin_to_unicode(Rest, <<Acc/binary, U/utf8>>).

bin_from_unicode(<<>>, Bin) -> Bin;
bin_from_unicode(<<U/utf8, Rest/binary>>, Acc) ->
    C = from_unicode(U),
    bin_from_unicode(Rest, <<Acc/binary, C>>).
