%% THIS FILE WAS AUTOMATICALLY GENERATED BY gen_src.pl
%% FROM mappings/ISO8859/8859-10.TXT AT 2016-08-19
-module(iso8859_10).
-vsn(20160819).
-export([to_unicode/1, from_unicode/1]).

%% Public functions
to_unicode(16#A1) -> 16#0104;
to_unicode(16#A2) -> 16#0112;
to_unicode(16#A3) -> 16#0122;
to_unicode(16#A4) -> 16#012A;
to_unicode(16#A5) -> 16#0128;
to_unicode(16#A6) -> 16#0136;
to_unicode(16#A8) -> 16#013B;
to_unicode(16#A9) -> 16#0110;
to_unicode(16#AA) -> 16#0160;
to_unicode(16#AB) -> 16#0166;
to_unicode(16#AC) -> 16#017D;
to_unicode(16#AE) -> 16#016A;
to_unicode(16#AF) -> 16#014A;
to_unicode(16#B1) -> 16#0105;
to_unicode(16#B2) -> 16#0113;
to_unicode(16#B3) -> 16#0123;
to_unicode(16#B4) -> 16#012B;
to_unicode(16#B5) -> 16#0129;
to_unicode(16#B6) -> 16#0137;
to_unicode(16#B8) -> 16#013C;
to_unicode(16#B9) -> 16#0111;
to_unicode(16#BA) -> 16#0161;
to_unicode(16#BB) -> 16#0167;
to_unicode(16#BC) -> 16#017E;
to_unicode(16#BD) -> 16#2015;
to_unicode(16#BE) -> 16#016B;
to_unicode(16#BF) -> 16#014B;
to_unicode(16#C0) -> 16#0100;
to_unicode(16#C7) -> 16#012E;
to_unicode(16#C8) -> 16#010C;
to_unicode(16#CA) -> 16#0118;
to_unicode(16#CC) -> 16#0116;
to_unicode(16#D1) -> 16#0145;
to_unicode(16#D2) -> 16#014C;
to_unicode(16#D7) -> 16#0168;
to_unicode(16#D9) -> 16#0172;
to_unicode(16#E0) -> 16#0101;
to_unicode(16#E7) -> 16#012F;
to_unicode(16#E8) -> 16#010D;
to_unicode(16#EA) -> 16#0119;
to_unicode(16#EC) -> 16#0117;
to_unicode(16#F1) -> 16#0146;
to_unicode(16#F2) -> 16#014D;
to_unicode(16#F7) -> 16#0169;
to_unicode(16#F9) -> 16#0173;
to_unicode(16#FF) -> 16#0138;
to_unicode(List) when is_list(List) -> [to_unicode(C) || C <- List];
to_unicode(Bin) when is_binary(Bin) -> bin_to_unicode(Bin, <<>>);
to_unicode(Other) -> Other.

from_unicode(16#0104) -> 16#A1;
from_unicode(16#0112) -> 16#A2;
from_unicode(16#0122) -> 16#A3;
from_unicode(16#012A) -> 16#A4;
from_unicode(16#0128) -> 16#A5;
from_unicode(16#0136) -> 16#A6;
from_unicode(16#013B) -> 16#A8;
from_unicode(16#0110) -> 16#A9;
from_unicode(16#0160) -> 16#AA;
from_unicode(16#0166) -> 16#AB;
from_unicode(16#017D) -> 16#AC;
from_unicode(16#016A) -> 16#AE;
from_unicode(16#014A) -> 16#AF;
from_unicode(16#0105) -> 16#B1;
from_unicode(16#0113) -> 16#B2;
from_unicode(16#0123) -> 16#B3;
from_unicode(16#012B) -> 16#B4;
from_unicode(16#0129) -> 16#B5;
from_unicode(16#0137) -> 16#B6;
from_unicode(16#013C) -> 16#B8;
from_unicode(16#0111) -> 16#B9;
from_unicode(16#0161) -> 16#BA;
from_unicode(16#0167) -> 16#BB;
from_unicode(16#017E) -> 16#BC;
from_unicode(16#2015) -> 16#BD;
from_unicode(16#016B) -> 16#BE;
from_unicode(16#014B) -> 16#BF;
from_unicode(16#0100) -> 16#C0;
from_unicode(16#012E) -> 16#C7;
from_unicode(16#010C) -> 16#C8;
from_unicode(16#0118) -> 16#CA;
from_unicode(16#0116) -> 16#CC;
from_unicode(16#0145) -> 16#D1;
from_unicode(16#014C) -> 16#D2;
from_unicode(16#0168) -> 16#D7;
from_unicode(16#0172) -> 16#D9;
from_unicode(16#0101) -> 16#E0;
from_unicode(16#012F) -> 16#E7;
from_unicode(16#010D) -> 16#E8;
from_unicode(16#0119) -> 16#EA;
from_unicode(16#0117) -> 16#EC;
from_unicode(16#0146) -> 16#F1;
from_unicode(16#014D) -> 16#F2;
from_unicode(16#0169) -> 16#F7;
from_unicode(16#0173) -> 16#F9;
from_unicode(16#0138) -> 16#FF;
from_unicode(List) when is_list(List) -> [from_unicode(C) || C <- List];
from_unicode(Bin) when is_binary(Bin) -> bin_from_unicode(Bin, <<>>);
from_unicode(Other) -> Other.

%% Private functions
bin_to_unicode(<<>>, Bin) -> Bin;
bin_to_unicode(<<C, Rest/binary>>, Acc) ->
    U = to_unicode(C),
    bin_to_unicode(Rest, <<Acc/binary, U/utf8>>).

bin_from_unicode(<<>>, Bin) -> Bin;
bin_from_unicode(<<U/utf8, Rest/binary>>, Acc) ->
    C = from_unicode(U),
    bin_from_unicode(Rest, <<Acc/binary, C>>).
