%% THIS FILE WAS AUTOMATICALLY GENERATED BY gen_src.pl
%% FROM mappings/ISO8859/8859-9.TXT AT 2016-08-19
-module(iso8859_9).
-vsn(20160819).
-export([to_unicode/1, from_unicode/1]).

%% Public functions
to_unicode(16#D0) -> 16#011E;
to_unicode(16#DD) -> 16#0130;
to_unicode(16#DE) -> 16#015E;
to_unicode(16#F0) -> 16#011F;
to_unicode(16#FD) -> 16#0131;
to_unicode(16#FE) -> 16#015F;
to_unicode(List) when is_list(List) -> [to_unicode(C) || C <- List];
to_unicode(Bin) when is_binary(Bin) -> bin_to_unicode(Bin, <<>>);
to_unicode(Other) -> Other.

from_unicode(16#011E) -> 16#D0;
from_unicode(16#0130) -> 16#DD;
from_unicode(16#015E) -> 16#DE;
from_unicode(16#011F) -> 16#F0;
from_unicode(16#0131) -> 16#FD;
from_unicode(16#015F) -> 16#FE;
from_unicode(List) when is_list(List) -> [from_unicode(C) || C <- List];
from_unicode(Bin) when is_binary(Bin) -> bin_from_unicode(Bin, <<>>);
from_unicode(Other) -> Other.

%% Private functions
bin_to_unicode(<<>>, Bin) -> Bin;
bin_to_unicode(<<C, Rest/binary>>, Acc) ->
    U = to_unicode(C),
    bin_to_unicode(Rest, <<Acc/binary, U/utf8>>).

bin_from_unicode(<<>>, Bin) -> Bin;
bin_from_unicode(<<U/utf8, Rest/binary>>, Acc) ->
    C = from_unicode(U),
    bin_from_unicode(Rest, <<Acc/binary, C>>).
